[build]
builder = "NIXPACKS"
buildCommand = "npm ci && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[phases.setup]
nixPackages = ["nodejs", "postgresql"]

# Environment variables will be set in the Railway dashboard

[environments]
  [environments.production]
    numReplicas = 1
    
  [environments.development]
    healthcheckPath = "/"
    numReplicas = 1
    
  [environments.preview]
    numReplicas = 1